# =========================================================================
#     This makefile was generated by
#     Bakefile 0.2.9 (http://www.bakefile.org)
#     Do not modify, all changes will be overwritten!
# =========================================================================



# -------------------------------------------------------------------------
# These are configurable options:
# -------------------------------------------------------------------------

#  
AR ?= ar

#  
RANLIB ?= ranlib

# C compiler 
CC = gcc

# Standard flags for CC 
CFLAGS ?= 

# Standard preprocessor flags (common for CC and CXX) 
CPPFLAGS ?= 

# Use debug build [0,1]
DEBUG ?= 1

# Use ICC build [0,1]
ICC ?= 0



# -------------------------------------------------------------------------
# Do not modify the rest of this file!
# -------------------------------------------------------------------------

### Variables: ###

CPPDEPS = -MT$@ -MF`echo $@ | sed -e 's,\.o$$,.d,'` -MD -MP
PNG_CFLAGS = -DUNA_PLATFORM_LINUX=1 -D_GNU_SOURCE -D_LARGEFILE_SOURCE \
	-D_FILE_OFFSET_BITS=64 -I./ -I../zlib/ $(__HC_OPTIMIZE_ENABLE_0) \
	$(__HC_DEBUG_ENABLE_1) -D_THREAD_SAFE -pthread -Wall -Wextra \
	-Wno-unused-parameter $(CPPFLAGS) $(CFLAGS)
PNG_OBJECTS =  \
	./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/png_png.o \
	./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/png_pngset.o \
	./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/png_pngget.o \
	./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/png_pngrutil.o \
	./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/png_pngtrans.o \
	./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/png_pngwutil.o \
	./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/png_pngread.o \
	./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/png_pngrio.o \
	./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/png_pngwio.o \
	./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/png_pngwrite.o \
	./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/png_pngrtran.o \
	./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/png_pngwtran.o \
	./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/png_pngmem.o \
	./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/png_pngerror.o \
	./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/png_pngpread.o

### Conditionally set variables: ###

ifeq ($(DEBUG),0)
HC_DR_DEFINE = release
endif
ifeq ($(DEBUG),1)
HC_DR_DEFINE = debug
endif
ifeq ($(ICC),0)
HC_DR_ICC_DEFINE = 
endif
ifeq ($(ICC),1)
HC_DR_ICC_DEFINE = -icc
endif
ifeq ($(DEBUG),0)
__HC_OPTIMIZE_ENABLE_0 = -O2
endif
ifeq ($(DEBUG),1)
__HC_OPTIMIZE_ENABLE_0 = 
endif
ifeq ($(DEBUG),0)
__HC_DEBUG_ENABLE_1 = 
endif
ifeq ($(DEBUG),1)
__HC_DEBUG_ENABLE_1 = -g
endif


all: ./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)
./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE):
	@mkdir -p ./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)

### Targets: ###

all: ./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/libpng.a

install: 

uninstall: 

clean: 
	rm -f ./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/*.o
	rm -f ./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/*.d
	rm -f ./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/libpng.a

./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/libpng.a: $(PNG_OBJECTS)
	rm -f $@
	$(AR) rcu $@ $(PNG_OBJECTS)
	$(RANLIB) $@
	cp -f ./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/libpng.a ./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/libpng.lib

./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/png_png.o: ./png.c
	$(CC) -c -o $@ $(PNG_CFLAGS) $(CPPDEPS) $<

./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/png_pngset.o: ./pngset.c
	$(CC) -c -o $@ $(PNG_CFLAGS) $(CPPDEPS) $<

./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/png_pngget.o: ./pngget.c
	$(CC) -c -o $@ $(PNG_CFLAGS) $(CPPDEPS) $<

./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/png_pngrutil.o: ./pngrutil.c
	$(CC) -c -o $@ $(PNG_CFLAGS) $(CPPDEPS) $<

./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/png_pngtrans.o: ./pngtrans.c
	$(CC) -c -o $@ $(PNG_CFLAGS) $(CPPDEPS) $<

./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/png_pngwutil.o: ./pngwutil.c
	$(CC) -c -o $@ $(PNG_CFLAGS) $(CPPDEPS) $<

./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/png_pngread.o: ./pngread.c
	$(CC) -c -o $@ $(PNG_CFLAGS) $(CPPDEPS) $<

./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/png_pngrio.o: ./pngrio.c
	$(CC) -c -o $@ $(PNG_CFLAGS) $(CPPDEPS) $<

./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/png_pngwio.o: ./pngwio.c
	$(CC) -c -o $@ $(PNG_CFLAGS) $(CPPDEPS) $<

./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/png_pngwrite.o: ./pngwrite.c
	$(CC) -c -o $@ $(PNG_CFLAGS) $(CPPDEPS) $<

./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/png_pngrtran.o: ./pngrtran.c
	$(CC) -c -o $@ $(PNG_CFLAGS) $(CPPDEPS) $<

./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/png_pngwtran.o: ./pngwtran.c
	$(CC) -c -o $@ $(PNG_CFLAGS) $(CPPDEPS) $<

./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/png_pngmem.o: ./pngmem.c
	$(CC) -c -o $@ $(PNG_CFLAGS) $(CPPDEPS) $<

./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/png_pngerror.o: ./pngerror.c
	$(CC) -c -o $@ $(PNG_CFLAGS) $(CPPDEPS) $<

./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/png_pngpread.o: ./pngpread.c
	$(CC) -c -o $@ $(PNG_CFLAGS) $(CPPDEPS) $<

.PHONY: all install uninstall clean


# Dependencies tracking:
-include ./bin/linux_$(HC_DR_DEFINE)$(HC_DR_ICC_DEFINE)/*.d
